### ISSUE TITLE
Module does not display in Rackv1

### ISSUE THREAD

**Issue by tank-trax** [KarateSnoopy/vcv-snoopy#10]
I am using Debian Stretch 9.9 and am able to build successfully however the modules do not display when searching them out in Rack V1

I tried to rename the slugs as per https://github.com/KarateSnoopy/vcv-karatesnoopy/issues/9 to no avail

**Comment by cschol** [comment]
Slugs in the `plugin.json` need to match the ones in the `createModel` function call in the source code.

**Comment by tank-trax** [comment]
still not displaying

**Comment by KarateSnoopy** [comment]
Ok, fixed now in v1 branch by https://github.com/KarateSnoopy/vcv-karatesnoopy/commit/4168a22c4fd90790697f8a2416472fe257153294
