### ISSUE TITLE
Random Pitch, Gate, Skip

### ISSUE THREAD

**Issue by blackearth2014** [KarateSnoopy/vcv-snoopy#3]
Random Pitch, Gate, Skip is not responding when selected. They only change when you select the main randomizing feature.

**Comment by aeuae** [comment]
also observed here on VCV 0.5.1/mac os high sierra.

**Comment by SteveRussell33** [comment]
Same here VCV 0.6.2c Win10

**Comment by KarateSnoopy** [comment]
Fixed in v1 port
