### ISSUE TITLE
Module build error

### ISSUE THREAD

**Issue by cschol** [KarateSnoopy/vcv-snoopy#8]
This does not compile with the `Rack SDK`:

```
In file included from src/SEQWidget.cpp:5:0:
src/SeqModule.h:7:10: fatal error: SEQModule.h: No such file or directory
 #include "SEQModule.h"
          ^~~~~~~~~~~~~
compilation terminated.
/home/cschol/src/Rack/compile.mk:64: recipe for target 'build/src/SEQWidget.cpp.o' failed
make: *** [build/src/SEQWidget.cpp.o] Error 1
make: *** Waiting for unfinished jobs....
In file included from src/SeqModule.cpp:1:0:
src/SeqModule.h:7:10: fatal error: SEQModule.h: No such file or directory
 #include "SEQModule.h"
          ^~~~~~~~~~~~~
compilation terminated.
/home/cschol/src/Rack/compile.mk:64: recipe for target 'build/src/SeqModule.cpp.o' failed
make: *** [build/src/SeqModule.cpp.o] Error 1
src/PluginInit.cpp:2:10: fatal error: SeqWidget.h: No such file or directory
 #include "SeqWidget.h"
          ^~~~~~~~~~~~~
compilation terminated.
/home/cschol/src/Rack/compile.mk:64: recipe for target 'build/src/PluginInit.cpp.o' failed
make: *** [build/src/PluginInit.cpp.o] Error 1
```

The code in the repo cannot build. Are you sure that you have the latest source pushed to the repo?

For example:

```
In file included from src/SEQWidget.cpp:5:0:
src/SeqModule.h:7:10: fatal error: SEQModule.h: No such file or directory
 #include "SEQModule.h"
```

There is no `SEQModule.h` file in the repository! It is called `SeqModule.h`.

**Comment by KarateSnoopy** [comment]
Hmm, I don't see SEQModule.h in the sources.  


F:\git\vcvrack-v0.6\plugins\KarateSnoopy>git reset --hard origin/master
HEAD is now at c2b628e Fixing build

F:\git\vcvrack-v0.6\plugins\KarateSnoopy>findstr /sip SEQModule.h *.cpp
src\PluginInit.cpp:#include "SeqModule.h"
src\SeqModule.cpp:#include "SeqModule.h"
src\SEQWidget.cpp:#include "SeqModule.h"

For example, see https://github.com/KarateSnoopy/vcv-karatesnoopy/blob/master/src/SeqModule.cpp#L1

**Comment by cschol** [comment]
It's not in the `.cpp` files! Look closely at the error message above. The include is in the `.h` file!

**Comment by KarateSnoopy** [comment]
Ah, I'll fix it up.  For some odd reason it builds on Windows.  Must be case sensitive on some platforms.

**Comment by cschol** [comment]
Thanks. That is weird. It must build on all platforms though, otherwise Andrew's build system will reject it. I'll check it out on Windows and Mac after you have pushed an update to make sure it works.

**Comment by KarateSnoopy** [comment]
Ok, try latest commit.  https://github.com/KarateSnoopy/vcv-karatesnoopy/commit/601db13428f86e5553aebc683daadd387eab8c37

**Comment by cschol** [comment]
Another error with `SeqWidget.h`:

```
src/PluginInit.cpp:2:10: fatal error: SeqWidget.h: No such file or directory
 #include "SeqWidget.h"
          ^~~~~~~~~~~~~
compilation terminated.
src/SEQWidget.cpp:6:10: fatal error: SeqWidget.h: No such file or directory
 #include "SeqWidget.h"
          ^~~~~~~~~~~~~
```

**Comment by cschol** [comment]
And lastly:

```
src/SEQWidget.cpp:6:10: fatal error: SeqWidget.h: No such file or directory
 #include "SeqWidget.h"
          ^~~~~~~~~~~~~
compilation terminated.
```

Then it compiles.

**Comment by KarateSnoopy** [comment]
Ok, try https://github.com/KarateSnoopy/vcv-karatesnoopy/commit/13c1af9356995a66a17f85bf3a66b043d61ef640

**Comment by KarateSnoopy** [comment]
btw, https://stackoverflow.com/a/9450096.  Windows file system isn't case sensitive so that's why I'm not seeing these errors.

**Comment by cschol** [comment]
That worked for Linux and Mac. We're good now. Thank you for fixing it.

**Comment by KarateSnoopy** [comment]
Thanks for the help! :)
